In [3]:
# pip install opencv-python
import cv2

In [2]:
img=cv2.imread("galaxy.jpg",0)

In [3]:
print(type(img))

<class 'numpy.ndarray'>


In [4]:
print(img)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [5]:
img.shape

(1485, 990)

In [7]:
1485*990

1470150

In [6]:
img.ndim

2

In [9]:
img3=cv2.imread("galaxy.jpg",1)

In [13]:
img3.shape

(1485, 990, 3)

In [12]:
img3.ndim

3

In [14]:
cv2.imshow("Galaxy",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
resized_image=cv2.resize(img,(1000,500))

In [16]:
resized_image.shape

(500, 1000)

In [17]:
cv2.imshow("Galaxy",resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import glob

In [2]:
images=glob.glob("*.jpg")

In [7]:
for image in images:
    img=cv2.imread(image,0)
    re=cv2.resize(img,(200,200))
    cv2.imshow("Hey",re)
    cv2.waitKey(5000)
    cv2.destroyAllWindows()
    cv2.imwrite("resized_"+image,re)